-- 전자정부 프레임워크 공통코드 테이블 구조
-- 참조 사이트와 동일한 구조로 수정 (CODE_ID, CODE 컬럼 길이 확장)

-- 공통코드 분류 테이블
CREATE TABLE IF NOT EXISTS COMTCCMMNCLCODE (
    CL_CODE CHAR(3) NOT NULL,
    CL_CODE_NM VARCHAR(60) DEFAULT NULL,
    CL_CODE_DC VARCHAR(200) DEFAULT NULL,
    USE_AT CHAR(1) DEFAULT NULL,
    FRST_REGIST_PNTTM DATETIME DEFAULT NULL,
    FRST_REGISTER_ID VARCHAR(20) DEFAULT NULL,
    LAST_UPDT_PNTTM DATETIME DEFAULT NULL,
    LAST_UPDUSR_ID VARCHAR(20) DEFAULT NULL,
    PRIMARY KEY (CL_CODE),
    UNIQUE KEY COMTCCMMNCLCODE_PK (CL_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- 공통코드 그룹 테이블 (CODE_ID 길이 확장)
CREATE TABLE IF NOT EXISTS COMTCCMMNCODE (
    CODE_ID VARCHAR(20) NOT NULL,
    CODE_ID_NM VARCHAR(60) DEFAULT NULL,
    CODE_ID_DC VARCHAR(200) DEFAULT NULL,
    USE_AT CHAR(1) DEFAULT NULL,
    CL_CODE CHAR(3) DEFAULT NULL,
    FRST_REGIST_PNTTM DATETIME DEFAULT NULL,
    FRST_REGISTER_ID VARCHAR(20) DEFAULT NULL,
    LAST_UPDT_PNTTM DATETIME DEFAULT NULL,
    LAST_UPDUSR_ID VARCHAR(20) DEFAULT NULL,
    PRIMARY KEY (CODE_ID),
    UNIQUE KEY COMTCCMMNCODE_PK (CODE_ID),
    KEY COMTCCMMNCODE_i01 (CL_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- 공통코드 상세 테이블 (CODE 길이 확장)
CREATE TABLE IF NOT EXISTS COMTCCMMNDETAILCODE (
    CODE_ID VARCHAR(20) NOT NULL,
    CODE VARCHAR(50) NOT NULL,
    CODE_NM VARCHAR(60) DEFAULT NULL,
    CODE_DC VARCHAR(200) DEFAULT NULL,
    USE_AT CHAR(1) DEFAULT NULL,
    FRST_REGIST_PNTTM DATETIME DEFAULT NULL,
    FRST_REGISTER_ID VARCHAR(20) DEFAULT NULL,
    LAST_UPDT_PNTTM DATETIME DEFAULT NULL,
    LAST_UPDUSR_ID VARCHAR(20) DEFAULT NULL,
    PRIMARY KEY (CODE_ID, CODE),
    UNIQUE KEY COMTCCMMNDETAILCODE_PK (CODE_ID, CODE),
    KEY COMTCCMMNDETAILCODE_i01 (CODE_ID),
    CONSTRAINT COMTCCMMNDETAILCODE_FK1 FOREIGN KEY (CODE_ID) REFERENCES COMTCCMMNCODE (CODE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- 공통코드 분류 데이터
INSERT INTO COMTCCMMNCLCODE (CL_CODE, CL_CODE_NM, CL_CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID) VALUES
('SYS', '시스템 코드', '시스템 관련 공통코드', 'Y', NOW(), 'SYSTEM');

-- 설문조사 관련 공통코드 그룹 데이터 (참조 사이트와 동일한 구조)
INSERT INTO COMTCCMMNCODE (CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, CL_CODE, FRST_REGIST_PNTTM, FRST_REGISTER_ID) VALUES
('SURVEY_STATUS', '설문 상태', '설문조사의 상태 구분', 'Y', 'SYS', NOW(), 'SYSTEM'),
('QUESTION_TYPE', '질문 유형', '설문 질문의 유형 구분', 'Y', 'SYS', NOW(), 'SYSTEM'),
('SURVEY_CATEGORY', '설문 카테고리', '설문조사의 카테고리 구분', 'Y', 'SYS', NOW(), 'SYSTEM'),
('ADMIN_AUTHORITY', '관리자 권한', '관리자 권한 구분', 'Y', 'SYS', NOW(), 'SYSTEM');

-- 설문 상태 코드 상세 (참조 사이트와 동일한 구조)
INSERT INTO COMTCCMMNDETAILCODE (CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID) VALUES
('SURVEY_STATUS', 'DRAFT', '임시저장', '설문 작성 중', 'Y', NOW(), 'SYSTEM'),
('SURVEY_STATUS', 'PUBLISHED', '배포중', '설문 배포 중', 'Y', NOW(), 'SYSTEM'),
('SURVEY_STATUS', 'CLOSED', '종료', '설문 종료', 'Y', NOW(), 'SYSTEM'),
('SURVEY_STATUS', 'ARCHIVED', '보관', '설문 보관', 'Y', NOW(), 'SYSTEM');

-- 질문 유형 코드 상세 (참조 사이트와 동일한 구조)
INSERT INTO COMTCCMMNDETAILCODE (CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID) VALUES
('QUESTION_TYPE', 'TEXT', '주관식', '자유 텍스트 입력', 'Y', NOW(), 'SYSTEM'),
('QUESTION_TYPE', 'RADIO', '객관식(단일)', '단일 선택 객관식', 'Y', NOW(), 'SYSTEM'),
('QUESTION_TYPE', 'CHECKBOX', '객관식(복수)', '복수 선택 객관식', 'Y', NOW(), 'SYSTEM'),
('QUESTION_TYPE', 'SCALE', '척도형', '1-5점 척도', 'Y', NOW(), 'SYSTEM'),
('QUESTION_TYPE', 'DATE', '날짜', '날짜 선택', 'Y', NOW(), 'SYSTEM'),
('QUESTION_TYPE', 'FILE', '파일업로드', '파일 업로드', 'Y', NOW(), 'SYSTEM');

-- 설문 카테고리 코드 상세 (참조 사이트와 동일한 구조)
INSERT INTO COMTCCMMNDETAILCODE (CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID) VALUES
('SURVEY_CATEGORY', 'CUSTOMER_SATISFACTION', '고객만족도', '고객 만족도 조사', 'Y', NOW(), 'SYSTEM'),
('SURVEY_CATEGORY', 'MARKET_RESEARCH', '시장조사', '시장 조사', 'Y', NOW(), 'SYSTEM'),
('SURVEY_CATEGORY', 'EMPLOYEE_SATISFACTION', '직원만족도', '직원 만족도 조사', 'Y', NOW(), 'SYSTEM'),
('SURVEY_CATEGORY', 'ACADEMIC_RESEARCH', '학술조사', '학술 연구 조사', 'Y', NOW(), 'SYSTEM'),
('SURVEY_CATEGORY', 'SOCIAL_RESEARCH', '사회조사', '사회 현상 조사', 'Y', NOW(), 'SYSTEM'),
('SURVEY_CATEGORY', 'ETC', '기타', '기타 설문조사', 'Y', NOW(), 'SYSTEM');

-- 관리자 권한 상세코드 (참조 사이트와 동일)
INSERT INTO COMTCCMMNDETAILCODE (CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID) VALUES
('ADMIN_AUTHORITY', 'SYSTEM_ADMIN', '시스템 관리자', '시스템 전체 관리 권한', 'Y', NOW(), 'SYSTEM'),
('ADMIN_AUTHORITY', 'SUPER_ADMIN', '슈퍼 관리자', '슈퍼 관리자 권한', 'Y', NOW(), 'SYSTEM'),
('ADMIN_AUTHORITY', 'STAFF_ADMIN', '직원 관리자', '직원 관리 권한', 'Y', NOW(), 'SYSTEM'),
('ADMIN_AUTHORITY', 'ADMIN', '업무 관리자', '업무 관리 권한', 'Y', NOW(), 'SYSTEM');

COMMIT; 