-- 전자정부 프레임워크 공통코드 테이블 구조 (PostgreSQL)
-- COMTCCMMNCLCODE: 공통분류코드
-- COMTCCMMNCODE: 공통코드
-- COMTCCMMNDETAILCODE: 공통상세코드

-- 공통분류코드 테이블
CREATE TABLE IF NOT EXISTS COMTCCMMNCLCODE (
    CL_CODE VARCHAR(3) NOT NULL,
    CL_CODE_NM VARCHAR(60) NOT NULL,
    CL_CODE_DC VARCHAR(200),
    USE_AT CHAR(1) DEFAULT 'Y',
    FRST_REGIST_PNTTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FRST_REGISTER_ID VARCHAR(20),
    LAST_UPDT_PNTTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDUSR_ID VARCHAR(20),
    PRIMARY KEY (CL_CODE)
);

-- 공통코드 테이블
CREATE TABLE IF NOT EXISTS COMTCCMMNCODE (
    CODE_ID VARCHAR(6) NOT NULL,
    CODE_ID_NM VARCHAR(60) NOT NULL,
    CODE_ID_DC VARCHAR(200),
    USE_AT CHAR(1) DEFAULT 'Y',
    CL_CODE VARCHAR(3),
    FRST_REGIST_PNTTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FRST_REGISTER_ID VARCHAR(20),
    LAST_UPDT_PNTTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDUSR_ID VARCHAR(20),
    PRIMARY KEY (CODE_ID),
    FOREIGN KEY (CL_CODE) REFERENCES COMTCCMMNCLCODE(CL_CODE)
);

-- 공통상세코드 테이블
CREATE TABLE IF NOT EXISTS COMTCCMMNDETAILCODE (
    CODE_ID VARCHAR(6) NOT NULL,
    CODE VARCHAR(15) NOT NULL,
    CODE_NM VARCHAR(60) NOT NULL,
    CODE_DC VARCHAR(200),
    USE_AT CHAR(1) DEFAULT 'Y',
    CODE_ORDER INTEGER DEFAULT 0,
    FRST_REGIST_PNTTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FRST_REGISTER_ID VARCHAR(20),
    LAST_UPDT_PNTTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDUSR_ID VARCHAR(20),
    PRIMARY KEY (CODE_ID, CODE),
    FOREIGN KEY (CODE_ID) REFERENCES COMTCCMMNCODE(CODE_ID)
);

-- 샘플 데이터 삽입

-- 공통분류코드 샘플 데이터
INSERT INTO COMTCCMMNCLCODE (CL_CODE, CL_CODE_NM, CL_CODE_DC, USE_AT, FRST_REGISTER_ID) VALUES
('COM', '공통', '공통 분류 코드', 'Y', 'SYSTEM'),
('SUR', '설문', '설문조사 관련 코드', 'Y', 'SYSTEM')
ON CONFLICT (CL_CODE) DO NOTHING;

-- 공통코드 샘플 데이터
INSERT INTO COMTCCMMNCODE (CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, CL_CODE, FRST_REGISTER_ID) VALUES
('COM001', '사용자 구분', '사용자 유형 구분 코드', 'Y', 'COM', 'SYSTEM'),
('COM002', '성별', '성별 구분 코드', 'Y', 'COM', 'SYSTEM'),
('SUR001', '설문 유형', '설문조사 유형 구분 코드', 'Y', 'SUR', 'SYSTEM'),
('SUR002', '설문 상태', '설문조사 상태 구분 코드', 'Y', 'SUR', 'SYSTEM')
ON CONFLICT (CODE_ID) DO NOTHING;

-- 공통상세코드 샘플 데이터
INSERT INTO COMTCCMMNDETAILCODE (CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, CODE_ORDER, FRST_REGISTER_ID) VALUES
-- 사용자 구분
('COM001', 'ADMIN', '관리자', '시스템 관리자', 'Y', 1, 'SYSTEM'),
('COM001', 'USER', '일반사용자', '일반 사용자', 'Y', 2, 'SYSTEM'),
('COM001', 'GUEST', '게스트', '게스트 사용자', 'Y', 3, 'SYSTEM'),

-- 성별
('COM002', 'M', '남성', '남성', 'Y', 1, 'SYSTEM'),
('COM002', 'F', '여성', '여성', 'Y', 2, 'SYSTEM'),

-- 설문 유형
('SUR001', 'SURVEY', '일반설문', '일반 설문조사', 'Y', 1, 'SYSTEM'),
('SUR001', 'POLL', '투표', '투표형 설문조사', 'Y', 2, 'SYSTEM'),
('SUR001', 'QUIZ', '퀴즈', '퀴즈형 설문조사', 'Y', 3, 'SYSTEM'),

-- 설문 상태
('SUR002', 'DRAFT', '작성중', '설문 작성 중', 'Y', 1, 'SYSTEM'),
('SUR002', 'PUBLISHED', '배포중', '설문 배포 중', 'Y', 2, 'SYSTEM'),
('SUR002', 'CLOSED', '마감', '설문 마감', 'Y', 3, 'SYSTEM'),
('SUR002', 'DELETED', '삭제', '설문 삭제', 'Y', 4, 'SYSTEM')
ON CONFLICT (CODE_ID, CODE) DO NOTHING;

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS IDX_COMTCCMMNCODE_CL_CODE ON COMTCCMMNCODE(CL_CODE);
CREATE INDEX IF NOT EXISTS IDX_COMTCCMMNCODE_USE_AT ON COMTCCMMNCODE(USE_AT);
CREATE INDEX IF NOT EXISTS IDX_COMTCCMMNDETAILCODE_CODE_ID ON COMTCCMMNDETAILCODE(CODE_ID);
CREATE INDEX IF NOT EXISTS IDX_COMTCCMMNDETAILCODE_USE_AT ON COMTCCMMNDETAILCODE(USE_AT);
CREATE INDEX IF NOT EXISTS IDX_COMTCCMMNDETAILCODE_CODE_ORDER ON COMTCCMMNDETAILCODE(CODE_ORDER); 