-- 전자정부 프레임워크 4.3.0 표준 로그인/인증 관련 테이블들을 생성하는 SQL 파일을 작성합니다.
-- 서버: 211.39.158.101:3306
-- 사용자: root
-- 스키마: opensurvey

-- 데이터베이스 사용
USE opensurvey;

-- =============================================
-- 1. 사용자 관리 테이블
-- =============================================

-- 사용자 기본 정보 테이블
CREATE TABLE IF NOT EXISTS COMTNEMPLYRINFO (
    ESNTL_ID VARCHAR(20) NOT NULL COMMENT '고유ID',
    EMPLYR_ID VARCHAR(20) NOT NULL COMMENT '업무사용자ID',
    USER_NM VARCHAR(60) NOT NULL COMMENT '사용자명',
    PASSWORD VARCHAR(200) NOT NULL COMMENT '비밀번호',
    HOUSE_ADRES VARCHAR(100) COMMENT '주소',
    DETAIL_ADRES VARCHAR(100) COMMENT '상세주소',
    ZIP_CODE VARCHAR(6) COMMENT '우편번호',
    OFFM_TELNO VARCHAR(20) COMMENT '회사전화번호',
    MBTLNUM VARCHAR(20) COMMENT '이동전화번호',
    EMAIL_ADRES VARCHAR(50) COMMENT '이메일주소',
    OFCPS_NM VARCHAR(50) COMMENT '직위명',
    HOUSE_END_TELNO VARCHAR(4) COMMENT '집전화번호',
    GROUP_ID VARCHAR(20) COMMENT '그룹ID',
    PSTINST_CODE VARCHAR(20) COMMENT '소속기관코드',
    EMPLYR_STTUS_CODE VARCHAR(1) NOT NULL COMMENT '업무사용자상태코드',
    ESNTL_ID_2 VARCHAR(20) COMMENT '고유ID2',
    ESNTL_ID_3 VARCHAR(20) COMMENT '고유ID3',
    ESNTL_ID_4 VARCHAR(20) COMMENT '고유ID4',
    ESNTL_ID_5 VARCHAR(20) COMMENT '고유ID5',
    ESNTL_ID_6 VARCHAR(20) COMMENT '고유ID6',
    ESNTL_ID_7 VARCHAR(20) COMMENT '고유ID7',
    ESNTL_ID_8 VARCHAR(20) COMMENT '고유ID8',
    ESNTL_ID_9 VARCHAR(20) COMMENT '고유ID9',
    ESNTL_ID_10 VARCHAR(20) COMMENT '고유ID10',
    ESNTL_ID_11 VARCHAR(20) COMMENT '고유ID11',
    ESNTL_ID_12 VARCHAR(20) COMMENT '고유ID12',
    ESNTL_ID_13 VARCHAR(20) COMMENT '고유ID13',
    ESNTL_ID_14 VARCHAR(20) COMMENT '고유ID14',
    ESNTL_ID_15 VARCHAR(20) COMMENT '고유ID15',
    ESNTL_ID_16 VARCHAR(20) COMMENT '고유ID16',
    ESNTL_ID_17 VARCHAR(20) COMMENT '고유ID17',
    ESNTL_ID_18 VARCHAR(20) COMMENT '고유ID18',
    ESNTL_ID_19 VARCHAR(20) COMMENT '고유ID19',
    ESNTL_ID_20 VARCHAR(20) COMMENT '고유ID20',
    ESNTL_ID_21 VARCHAR(20) COMMENT '고유ID21',
    ESNTL_ID_22 VARCHAR(20) COMMENT '고유ID22',
    ESNTL_ID_23 VARCHAR(20) COMMENT '고유ID23',
    ESNTL_ID_24 VARCHAR(20) COMMENT '고유ID24',
    ESNTL_ID_25 VARCHAR(20) COMMENT '고유ID25',
    ESNTL_ID_26 VARCHAR(20) COMMENT '고유ID26',
    ESNTL_ID_27 VARCHAR(20) COMMENT '고유ID27',
    ESNTL_ID_28 VARCHAR(20) COMMENT '고유ID28',
    ESNTL_ID_29 VARCHAR(20) COMMENT '고유ID29',
    ESNTL_ID_30 VARCHAR(20) COMMENT '고유ID30',
    ESNTL_ID_31 VARCHAR(20) COMMENT '고유ID31',
    ESNTL_ID_32 VARCHAR(20) COMMENT '고유ID32',
    ESNTL_ID_33 VARCHAR(20) COMMENT '고유ID33',
    ESNTL_ID_34 VARCHAR(20) COMMENT '고유ID34',
    ESNTL_ID_35 VARCHAR(20) COMMENT '고유ID35',
    ESNTL_ID_36 VARCHAR(20) COMMENT '고유ID36',
    ESNTL_ID_37 VARCHAR(20) COMMENT '고유ID37',
    ESNTL_ID_38 VARCHAR(20) COMMENT '고유ID38',
    ESNTL_ID_39 VARCHAR(20) COMMENT '고유ID39',
    ESNTL_ID_40 VARCHAR(20) COMMENT '고유ID40',
    ESNTL_ID_41 VARCHAR(20) COMMENT '고유ID41',
    ESNTL_ID_42 VARCHAR(20) COMMENT '고유ID42',
    ESNTL_ID_43 VARCHAR(20) COMMENT '고유ID43',
    ESNTL_ID_44 VARCHAR(20) COMMENT '고유ID44',
    ESNTL_ID_45 VARCHAR(20) COMMENT '고유ID45',
    ESNTL_ID_46 VARCHAR(20) COMMENT '고유ID46',
    ESNTL_ID_47 VARCHAR(20) COMMENT '고유ID47',
    ESNTL_ID_48 VARCHAR(20) COMMENT '고유ID48',
    ESNTL_ID_49 VARCHAR(20) COMMENT '고유ID49',
    ESNTL_ID_50 VARCHAR(20) COMMENT '고유ID50',
    ESNTL_ID_51 VARCHAR(20) COMMENT '고유ID51',
    ESNTL_ID_52 VARCHAR(20) COMMENT '고유ID52',
    ESNTL_ID_53 VARCHAR(20) COMMENT '고유ID53',
    ESNTL_ID_54 VARCHAR(20) COMMENT '고유ID54',
    ESNTL_ID_55 VARCHAR(20) COMMENT '고유ID55',
    ESNTL_ID_56 VARCHAR(20) COMMENT '고유ID56',
    ESNTL_ID_57 VARCHAR(20) COMMENT '고유ID57',
    ESNTL_ID_58 VARCHAR(20) COMMENT '고유ID58',
    ESNTL_ID_59 VARCHAR(20) COMMENT '고유ID59',
    ESNTL_ID_60 VARCHAR(20) COMMENT '고유ID60',
    ESNTL_ID_61 VARCHAR(20) COMMENT '고유ID61',
    ESNTL_ID_62 VARCHAR(20) COMMENT '고유ID62',
    ESNTL_ID_63 VARCHAR(20) COMMENT '고유ID63',
    ESNTL_ID_64 VARCHAR(20) COMMENT '고유ID64',
    ESNTL_ID_65 VARCHAR(20) COMMENT '고유ID65',
    ESNTL_ID_66 VARCHAR(20) COMMENT '고유ID66',
    ESNTL_ID_67 VARCHAR(20) COMMENT '고유ID67',
    ESNTL_ID_68 VARCHAR(20) COMMENT '고유ID68',
    ESNTL_ID_69 VARCHAR(20) COMMENT '고유ID69',
    ESNTL_ID_70 VARCHAR(20) COMMENT '고유ID70',
    ESNTL_ID_71 VARCHAR(20) COMMENT '고유ID71',
    ESNTL_ID_72 VARCHAR(20) COMMENT '고유ID72',
    ESNTL_ID_73 VARCHAR(20) COMMENT '고유ID73',
    ESNTL_ID_74 VARCHAR(20) COMMENT '고유ID74',
    ESNTL_ID_75 VARCHAR(20) COMMENT '고유ID75',
    ESNTL_ID_76 VARCHAR(20) COMMENT '고유ID76',
    ESNTL_ID_77 VARCHAR(20) COMMENT '고유ID77',
    ESNTL_ID_78 VARCHAR(20) COMMENT '고유ID78',
    ESNTL_ID_79 VARCHAR(20) COMMENT '고유ID79',
    ESNTL_ID_80 VARCHAR(20) COMMENT '고유ID80',
    ESNTL_ID_81 VARCHAR(20) COMMENT '고유ID81',
    ESNTL_ID_82 VARCHAR(20) COMMENT '고유ID82',
    ESNTL_ID_83 VARCHAR(20) COMMENT '고유ID83',
    ESNTL_ID_84 VARCHAR(20) COMMENT '고유ID84',
    ESNTL_ID_85 VARCHAR(20) COMMENT '고유ID85',
    ESNTL_ID_86 VARCHAR(20) COMMENT '고유ID86',
    ESNTL_ID_87 VARCHAR(20) COMMENT '고유ID87',
    ESNTL_ID_88 VARCHAR(20) COMMENT '고유ID88',
    ESNTL_ID_89 VARCHAR(20) COMMENT '고유ID89',
    ESNTL_ID_90 VARCHAR(20) COMMENT '고유ID90',
    ESNTL_ID_91 VARCHAR(20) COMMENT '고유ID91',
    ESNTL_ID_92 VARCHAR(20) COMMENT '고유ID92',
    ESNTL_ID_93 VARCHAR(20) COMMENT '고유ID93',
    ESNTL_ID_94 VARCHAR(20) COMMENT '고유ID94',
    ESNTL_ID_95 VARCHAR(20) COMMENT '고유ID95',
    ESNTL_ID_96 VARCHAR(20) COMMENT '고유ID96',
    ESNTL_ID_97 VARCHAR(20) COMMENT '고유ID97',
    ESNTL_ID_98 VARCHAR(20) COMMENT '고유ID98',
    ESNTL_ID_99 VARCHAR(20) COMMENT '고유ID99',
    ESNTL_ID_100 VARCHAR(20) COMMENT '고유ID100',
    SBSCRB_DE DATETIME COMMENT '가입일자',
    SEXDSTN_CODE VARCHAR(1) COMMENT '성별코드',
    BRTHDY VARCHAR(20) COMMENT '생년월일',
    FXNUM VARCHAR(20) COMMENT '팩스번호',
    EMPLYR_PHOTO_FILE_NM VARCHAR(60) COMMENT '업무사용자사진파일명',
    EMPLYR_PHOTO_FILE_COURS VARCHAR(255) COMMENT '업무사용자사진파일경로',
    EMPLYR_PHOTO_FILE_SIZE DECIMAL(10,0) COMMENT '업무사용자사진파일크기',
    EMPLYR_PHOTO_FILE_MIMETP VARCHAR(60) COMMENT '업무사용자사진파일MIME타입',
    EMPLYR_PHOTO_FILE_CN VARCHAR(4000) COMMENT '업무사용자사진파일내용',
    EMPLYR_PHOTO_FILE_DC VARCHAR(100) COMMENT '업무사용자사진파일설명',
    EMPLYR_PHOTO_FILE_ATCHMNTLY VARCHAR(1) COMMENT '업무사용자사진파일첨부여부',
    EMPLYR_PHOTO_FILE_ATCHMNTLY2 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부2',
    EMPLYR_PHOTO_FILE_ATCHMNTLY3 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부3',
    EMPLYR_PHOTO_FILE_ATCHMNTLY4 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부4',
    EMPLYR_PHOTO_FILE_ATCHMNTLY5 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부5',
    EMPLYR_PHOTO_FILE_ATCHMNTLY6 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부6',
    EMPLYR_PHOTO_FILE_ATCHMNTLY7 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부7',
    EMPLYR_PHOTO_FILE_ATCHMNTLY8 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부8',
    EMPLYR_PHOTO_FILE_ATCHMNTLY9 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부9',
    EMPLYR_PHOTO_FILE_ATCHMNTLY10 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부10',
    EMPLYR_PHOTO_FILE_ATCHMNTLY11 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부11',
    EMPLYR_PHOTO_FILE_ATCHMNTLY12 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부12',
    EMPLYR_PHOTO_FILE_ATCHMNTLY13 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부13',
    EMPLYR_PHOTO_FILE_ATCHMNTLY14 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부14',
    EMPLYR_PHOTO_FILE_ATCHMNTLY15 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부15',
    EMPLYR_PHOTO_FILE_ATCHMNTLY16 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부16',
    EMPLYR_PHOTO_FILE_ATCHMNTLY17 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부17',
    EMPLYR_PHOTO_FILE_ATCHMNTLY18 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부18',
    EMPLYR_PHOTO_FILE_ATCHMNTLY19 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부19',
    EMPLYR_PHOTO_FILE_ATCHMNTLY20 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부20',
    EMPLYR_PHOTO_FILE_ATCHMNTLY21 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부21',
    EMPLYR_PHOTO_FILE_ATCHMNTLY22 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부22',
    EMPLYR_PHOTO_FILE_ATCHMNTLY23 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부23',
    EMPLYR_PHOTO_FILE_ATCHMNTLY24 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부24',
    EMPLYR_PHOTO_FILE_ATCHMNTLY25 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부25',
    EMPLYR_PHOTO_FILE_ATCHMNTLY26 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부26',
    EMPLYR_PHOTO_FILE_ATCHMNTLY27 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부27',
    EMPLYR_PHOTO_FILE_ATCHMNTLY28 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부28',
    EMPLYR_PHOTO_FILE_ATCHMNTLY29 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부29',
    EMPLYR_PHOTO_FILE_ATCHMNTLY30 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부30',
    EMPLYR_PHOTO_FILE_ATCHMNTLY31 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부31',
    EMPLYR_PHOTO_FILE_ATCHMNTLY32 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부32',
    EMPLYR_PHOTO_FILE_ATCHMNTLY33 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부33',
    EMPLYR_PHOTO_FILE_ATCHMNTLY34 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부34',
    EMPLYR_PHOTO_FILE_ATCHMNTLY35 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부35',
    EMPLYR_PHOTO_FILE_ATCHMNTLY36 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부36',
    EMPLYR_PHOTO_FILE_ATCHMNTLY37 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부37',
    EMPLYR_PHOTO_FILE_ATCHMNTLY38 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부38',
    EMPLYR_PHOTO_FILE_ATCHMNTLY39 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부39',
    EMPLYR_PHOTO_FILE_ATCHMNTLY40 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부40',
    EMPLYR_PHOTO_FILE_ATCHMNTLY41 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부41',
    EMPLYR_PHOTO_FILE_ATCHMNTLY42 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부42',
    EMPLYR_PHOTO_FILE_ATCHMNTLY43 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부43',
    EMPLYR_PHOTO_FILE_ATCHMNTLY44 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부44',
    EMPLYR_PHOTO_FILE_ATCHMNTLY45 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부45',
    EMPLYR_PHOTO_FILE_ATCHMNTLY46 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부46',
    EMPLYR_PHOTO_FILE_ATCHMNTLY47 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부47',
    EMPLYR_PHOTO_FILE_ATCHMNTLY48 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부48',
    EMPLYR_PHOTO_FILE_ATCHMNTLY49 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부49',
    EMPLYR_PHOTO_FILE_ATCHMNTLY50 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부50',
    EMPLYR_PHOTO_FILE_ATCHMNTLY51 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부51',
    EMPLYR_PHOTO_FILE_ATCHMNTLY52 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부52',
    EMPLYR_PHOTO_FILE_ATCHMNTLY53 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부53',
    EMPLYR_PHOTO_FILE_ATCHMNTLY54 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부54',
    EMPLYR_PHOTO_FILE_ATCHMNTLY55 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부55',
    EMPLYR_PHOTO_FILE_ATCHMNTLY56 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부56',
    EMPLYR_PHOTO_FILE_ATCHMNTLY57 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부57',
    EMPLYR_PHOTO_FILE_ATCHMNTLY58 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부58',
    EMPLYR_PHOTO_FILE_ATCHMNTLY59 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부59',
    EMPLYR_PHOTO_FILE_ATCHMNTLY60 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부60',
    EMPLYR_PHOTO_FILE_ATCHMNTLY61 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부61',
    EMPLYR_PHOTO_FILE_ATCHMNTLY62 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부62',
    EMPLYR_PHOTO_FILE_ATCHMNTLY63 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부63',
    EMPLYR_PHOTO_FILE_ATCHMNTLY64 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부64',
    EMPLYR_PHOTO_FILE_ATCHMNTLY65 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부65',
    EMPLYR_PHOTO_FILE_ATCHMNTLY66 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부66',
    EMPLYR_PHOTO_FILE_ATCHMNTLY67 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부67',
    EMPLYR_PHOTO_FILE_ATCHMNTLY68 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부68',
    EMPLYR_PHOTO_FILE_ATCHMNTLY69 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부69',
    EMPLYR_PHOTO_FILE_ATCHMNTLY70 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부70',
    EMPLYR_PHOTO_FILE_ATCHMNTLY71 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부71',
    EMPLYR_PHOTO_FILE_ATCHMNTLY72 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부72',
    EMPLYR_PHOTO_FILE_ATCHMNTLY73 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부73',
    EMPLYR_PHOTO_FILE_ATCHMNTLY74 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부74',
    EMPLYR_PHOTO_FILE_ATCHMNTLY75 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부75',
    EMPLYR_PHOTO_FILE_ATCHMNTLY76 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부76',
    EMPLYR_PHOTO_FILE_ATCHMNTLY77 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부77',
    EMPLYR_PHOTO_FILE_ATCHMNTLY78 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부78',
    EMPLYR_PHOTO_FILE_ATCHMNTLY79 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부79',
    EMPLYR_PHOTO_FILE_ATCHMNTLY80 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부80',
    EMPLYR_PHOTO_FILE_ATCHMNTLY81 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부81',
    EMPLYR_PHOTO_FILE_ATCHMNTLY82 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부82',
    EMPLYR_PHOTO_FILE_ATCHMNTLY83 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부83',
    EMPLYR_PHOTO_FILE_ATCHMNTLY84 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부84',
    EMPLYR_PHOTO_FILE_ATCHMNTLY85 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부85',
    EMPLYR_PHOTO_FILE_ATCHMNTLY86 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부86',
    EMPLYR_PHOTO_FILE_ATCHMNTLY87 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부87',
    EMPLYR_PHOTO_FILE_ATCHMNTLY88 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부88',
    EMPLYR_PHOTO_FILE_ATCHMNTLY89 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부89',
    EMPLYR_PHOTO_FILE_ATCHMNTLY90 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부90',
    EMPLYR_PHOTO_FILE_ATCHMNTLY91 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부91',
    EMPLYR_PHOTO_FILE_ATCHMNTLY92 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부92',
    EMPLYR_PHOTO_FILE_ATCHMNTLY93 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부93',
    EMPLYR_PHOTO_FILE_ATCHMNTLY94 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부94',
    EMPLYR_PHOTO_FILE_ATCHMNTLY95 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부95',
    EMPLYR_PHOTO_FILE_ATCHMNTLY96 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부96',
    EMPLYR_PHOTO_FILE_ATCHMNTLY97 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부97',
    EMPLYR_PHOTO_FILE_ATCHMNTLY98 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부98',
    EMPLYR_PHOTO_FILE_ATCHMNTLY99 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부99',
    EMPLYR_PHOTO_FILE_ATCHMNTLY100 VARCHAR(1) COMMENT '업무사용자사진파일첨부여부100',
    FRST_REGIST_PNTTM DATETIME COMMENT '최초등록시점',
    FRST_REGISTER_ID VARCHAR(20) COMMENT '최초등록자ID',
    LAST_UPDT_PNTTM DATETIME COMMENT '최종수정시점',
    LAST_UPDUSR_ID VARCHAR(20) COMMENT '최종수정자ID',
    PRIMARY KEY (ESNTL_ID),
    UNIQUE KEY UK_COMTNEMPLYRINFO_01 (EMPLYR_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='업무사용자정보';

-- =============================================
-- 2. 권한 관리 테이블
-- =============================================

-- 권한 정보 테이블
CREATE TABLE IF NOT EXISTS COMTNAUTHORINFO (
    AUTHOR_CODE VARCHAR(30) NOT NULL COMMENT '권한코드',
    AUTHOR_NM VARCHAR(60) NOT NULL COMMENT '권한명',
    AUTHOR_DC VARCHAR(200) COMMENT '권한설명',
    AUTHOR_CREAT_DE CHAR(20) NOT NULL COMMENT '권한생성일',
    FRST_REGIST_PNTTM DATETIME COMMENT '최초등록시점',
    FRST_REGISTER_ID VARCHAR(20) COMMENT '최초등록자ID',
    LAST_UPDT_PNTTM DATETIME COMMENT '최종수정시점',
    LAST_UPDUSR_ID VARCHAR(20) COMMENT '최종수정자ID',
    PRIMARY KEY (AUTHOR_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='권한정보';

-- 사용자 권한 테이블
CREATE TABLE IF NOT EXISTS COMTNEMPLYRSCRTYESTBS (
    SCRTY_DTRMN_TRGET_ID VARCHAR(100) NOT NULL COMMENT '보안결정대상ID',
    MBER_TY_CODE VARCHAR(15) COMMENT '회원유형코드',
    AUTHOR_CODE VARCHAR(30) NOT NULL COMMENT '권한코드',
    PRIMARY KEY (SCRTY_DTRMN_TRGET_ID, AUTHOR_CODE),
    FOREIGN KEY (AUTHOR_CODE) REFERENCES COMTNAUTHORINFO(AUTHOR_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='업무사용자권한';

-- =============================================
-- 3. 메뉴 관리 테이블
-- =============================================

-- 메뉴 정보 테이블
CREATE TABLE IF NOT EXISTS COMTNMENUINFO (
    MENU_NM VARCHAR(60) NOT NULL COMMENT '메뉴명',
    PROGRM_FILE_NM VARCHAR(60) NOT NULL COMMENT '프로그램파일명',
    MENU_NO DECIMAL(20,0) NOT NULL COMMENT '메뉴번호',
    UPPER_MENU_NO DECIMAL(20,0) COMMENT '상위메뉴번호',
    MENU_ORDR DECIMAL(5,0) NOT NULL COMMENT '메뉴순서',
    MENU_DC VARCHAR(250) COMMENT '메뉴설명',
    RELATE_IMAGE_PATH VARCHAR(100) COMMENT '관련이미지경로',
    RELATE_IMAGE_NM VARCHAR(60) COMMENT '관련이미지명',
    FRST_REGIST_PNTTM DATETIME COMMENT '최초등록시점',
    FRST_REGISTER_ID VARCHAR(20) COMMENT '최초등록자ID',
    LAST_UPDT_PNTTM DATETIME COMMENT '최종수정시점',
    LAST_UPDUSR_ID VARCHAR(20) COMMENT '최종수정자ID',
    PRIMARY KEY (MENU_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='메뉴정보';

-- 메뉴 생성 테이블
CREATE TABLE IF NOT EXISTS COMTNMENUCREATDTLS (
    MENU_NO DECIMAL(20,0) NOT NULL COMMENT '메뉴번호',
    AUTHOR_CODE VARCHAR(30) NOT NULL COMMENT '권한코드',
    MAPNG_CREAT_ID VARCHAR(60) COMMENT '매핑생성ID',
    FRST_REGIST_PNTTM DATETIME COMMENT '최초등록시점',
    FRST_REGISTER_ID VARCHAR(20) COMMENT '최초등록자ID',
    LAST_UPDT_PNTTM DATETIME COMMENT '최종수정시점',
    LAST_UPDUSR_ID VARCHAR(20) COMMENT '최종수정자ID',
    PRIMARY KEY (MENU_NO, AUTHOR_CODE),
    FOREIGN KEY (MENU_NO) REFERENCES COMTNMENUINFO(MENU_NO),
    FOREIGN KEY (AUTHOR_CODE) REFERENCES COMTNAUTHORINFO(AUTHOR_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='메뉴생성내역';

-- =============================================
-- 4. 그룹 관리 테이블
-- =============================================

-- 그룹 정보 테이블
CREATE TABLE IF NOT EXISTS COMTNAUTHORGROUPINFO (
    GROUP_ID VARCHAR(20) NOT NULL COMMENT '그룹ID',
    GROUP_NM VARCHAR(60) NOT NULL COMMENT '그룹명',
    GROUP_CREAT_DE CHAR(20) NOT NULL COMMENT '그룹생성일',
    GROUP_DC VARCHAR(100) COMMENT '그룹설명',
    FRST_REGIST_PNTTM DATETIME COMMENT '최초등록시점',
    FRST_REGISTER_ID VARCHAR(20) COMMENT '최초등록자ID',
    LAST_UPDT_PNTTM DATETIME COMMENT '최종수정시점',
    LAST_UPDUSR_ID VARCHAR(20) COMMENT '최종수정자ID',
    PRIMARY KEY (GROUP_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='권한그룹정보';

-- =============================================
-- 5. 로그인 로그 테이블
-- =============================================

-- 로그인 로그 테이블
CREATE TABLE IF NOT EXISTS COMTNLOGINLOG (
    LOG_ID VARCHAR(20) NOT NULL COMMENT '로그ID',
    CONECT_ID VARCHAR(50) COMMENT '접속ID',
    CONECT_IP VARCHAR(23) COMMENT '접속IP',
    CONECT_MTHD VARCHAR(5) COMMENT '접속방법',
    ERROR_OCCRRNC_AT CHAR(1) COMMENT '오류발생여부',
    ERROR_CO VARCHAR(3) COMMENT '오류코드',
    CREAT_DT DATETIME COMMENT '생성일시',
    PRIMARY KEY (LOG_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='로그인로그';

-- =============================================
-- 6. 초기 데이터 삽입
-- =============================================

-- 관리자 권한 생성
INSERT INTO COMTNAUTHORINFO (AUTHOR_CODE, AUTHOR_NM, AUTHOR_DC, AUTHOR_CREAT_DE, FRST_REGIST_PNTTM, FRST_REGISTER_ID) VALUES
('ROLE_ADMIN', '관리자', '시스템 전체 관리 권한', '20240804', NOW(), 'SYSTEM'),
('ROLE_USER', '일반사용자', '일반 사용자 권한', '20240804', NOW(), 'SYSTEM'),
('ROLE_SURVEY_ADMIN', '설문관리자', '설문조사 관리 권한', '20240804', NOW(), 'SYSTEM');

-- 관리자 그룹 생성
INSERT INTO COMTNAUTHORGROUPINFO (GROUP_ID, GROUP_NM, GROUP_CREAT_DE, GROUP_DC, FRST_REGIST_PNTTM, FRST_REGISTER_ID) VALUES
('GROUP_001', '시스템관리자', '20240804', '시스템 전체 관리 그룹', NOW(), 'SYSTEM'),
('GROUP_002', '설문관리자', '20240804', '설문조사 관리 그룹', NOW(), 'SYSTEM'),
('GROUP_003', '일반사용자', '20240804', '일반 사용자 그룹', NOW(), 'SYSTEM');

-- 관리자 사용자 생성 (비밀번호: admin123)
INSERT INTO COMTNEMPLYRINFO (ESNTL_ID, EMPLYR_ID, USER_NM, PASSWORD, EMAIL_ADRES, OFCPS_NM, EMPLYR_STTUS_CODE, GROUP_ID, SBSCRB_DE, FRST_REGIST_PNTTM, FRST_REGISTER_ID) VALUES
('USRCNFRM_00000000001', 'admin', '시스템관리자', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVEFDa', 'admin@opensurvey.com', '시스템관리자', 'P', 'GROUP_001', '20240804', NOW(), 'SYSTEM');

-- 관리자 권한 부여
INSERT INTO COMTNEMPLYRSCRTYESTBS (SCRTY_DTRMN_TRGET_ID, MBER_TY_CODE, AUTHOR_CODE) VALUES
('admin', 'USR01', 'ROLE_ADMIN'),
('admin', 'USR01', 'ROLE_SURVEY_ADMIN');

-- 기본 메뉴 생성
INSERT INTO COMTNMENUINFO (MENU_NM, PROGRM_FILE_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, FRST_REGIST_PNTTM, FRST_REGISTER_ID) VALUES
('설문조사관리', '/admin/survey', 1, NULL, 1, '설문조사 관리 메뉴', NOW(), 'SYSTEM'),
('공통코드관리', '/admin/system/code', 2, NULL, 2, '공통코드 관리 메뉴', NOW(), 'SYSTEM'),
('사용자관리', '/admin/user', 3, NULL, 3, '사용자 관리 메뉴', NOW(), 'SYSTEM');

-- 메뉴 권한 부여
INSERT INTO COMTNMENUCREATDTLS (MENU_NO, AUTHOR_CODE, MAPNG_CREAT_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID) VALUES
(1, 'ROLE_ADMIN', 'MENU_001', NOW(), 'SYSTEM'),
(1, 'ROLE_SURVEY_ADMIN', 'MENU_002', NOW(), 'SYSTEM'),
(2, 'ROLE_ADMIN', 'MENU_003', NOW(), 'SYSTEM'),
(3, 'ROLE_ADMIN', 'MENU_004', NOW(), 'SYSTEM'); 