-- =====================================================
-- 전자정부 프레임워크 표준 게시판 테이블 확장
-- 게시판 유형별 게시물 속성 처리
-- OpenSurvey Project
-- =====================================================

-- 1. 게시판 마스터 테이블에 상태 컬럼 추가
ALTER TABLE COMTNBBSMST 
ADD COLUMN IF NOT EXISTS BBS_STATUS_CODE CHAR(6) DEFAULT 'BBSSTATUS01',
ADD COLUMN IF NOT EXISTS BBS_ORDER INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS BBS_DESCRIPTION TEXT;

COMMENT ON COLUMN COMTNBBSMST.BBS_STATUS_CODE IS '게시판상태코드';
COMMENT ON COLUMN COMTNBBSMST.BBS_ORDER IS '게시판정렬순서';
COMMENT ON COLUMN COMTNBBSMST.BBS_DESCRIPTION IS '게시판상세설명';

-- 2. 게시글 테이블에 게시판별 추가 속성 컬럼들 추가
ALTER TABLE COMTNBBS 
ADD COLUMN IF NOT EXISTS NTT_TAG VARCHAR(500),           -- 태그 (블로그게시판용)
ADD COLUMN IF NOT EXISTS NTT_CATEGORY VARCHAR(100),       -- 카테고리 (FAQ, QNA게시판용)
ADD COLUMN IF NOT EXISTS NTT_PRIORITY INTEGER DEFAULT 0,  -- 우선순위 (공지게시판용)
ADD COLUMN IF NOT EXISTS NTT_EXPIRY_DATE DATE,           -- 만료일 (공지게시판용)
ADD COLUMN IF NOT EXISTS NTT_VIEW_COUNT INTEGER DEFAULT 0, -- 조회수 (모든 게시판)
ADD COLUMN IF NOT EXISTS NTT_LIKE_COUNT INTEGER DEFAULT 0, -- 좋아요수 (커뮤니티게시판용)
ADD COLUMN IF NOT EXISTS NTT_STATUS_CODE CHAR(6) DEFAULT 'NTTSTATUS01'; -- 게시글상태

COMMENT ON COLUMN COMTNBBS.NTT_TAG IS '게시글태그';
COMMENT ON COLUMN COMTNBBS.NTT_CATEGORY IS '게시글카테고리';
COMMENT ON COLUMN COMTNBBS.NTT_PRIORITY IS '게시글우선순위';
COMMENT ON COLUMN COMTNBBS.NTT_EXPIRY_DATE IS '게시글만료일';
COMMENT ON COLUMN COMTNBBS.NTT_VIEW_COUNT IS '게시글조회수';
COMMENT ON COLUMN COMTNBBS.NTT_LIKE_COUNT IS '게시글좋아요수';
COMMENT ON COLUMN COMTNBBS.NTT_STATUS_CODE IS '게시글상태코드';

-- 3. 게시글 상태 공통코드 생성
INSERT INTO COMTCCMMNCODE (CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, CL_CODE, FRST_REGISTER_ID) 
VALUES ('NTTSTATUS', '게시글상태', '게시글의 상태를 관리하는 코드', 'Y', 'COM', 'SYSTEM')
ON CONFLICT (CODE_ID) DO NOTHING;

INSERT INTO COMTCCMMNDETAILCODE (CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, CODE_ORDER, FRST_REGISTER_ID) VALUES
('NTTSTATUS', 'NTTSTATUS01', '정상', '정상적으로 표시되는 게시글', 'Y', 1, 'SYSTEM'),
('NTTSTATUS', 'NTTSTATUS02', '임시저장', '임시저장된 게시글', 'Y', 2, 'SYSTEM'),
('NTTSTATUS', 'NTTSTATUS03', '승인대기', '승인을 기다리는 게시글', 'Y', 3, 'SYSTEM'),
('NTTSTATUS', 'NTTSTATUS04', '승인거부', '승인이 거부된 게시글', 'Y', 4, 'SYSTEM'),
('NTTSTATUS', 'NTTSTATUS05', '삭제', '삭제된 게시글', 'Y', 5, 'SYSTEM')
ON CONFLICT (CODE_ID, CODE) DO NOTHING;

-- 4. 게시글 카테고리 공통코드 생성 (FAQ, QNA용)
INSERT INTO COMTCCMMNCODE (CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, CL_CODE, FRST_REGISTER_ID) 
VALUES ('NTTCATEGORY', '게시글카테고리', '게시글의 카테고리를 구분하는 코드', 'Y', 'COM', 'SYSTEM')
ON CONFLICT (CODE_ID) DO NOTHING;

INSERT INTO COMTCCMMNDETAILCODE (CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, CODE_ORDER, FRST_REGISTER_ID) VALUES
('NTTCATEGORY', 'NTTCAT01', '일반', '일반적인 게시글', 'Y', 1, 'SYSTEM'),
('NTTCATEGORY', 'NTTCAT02', '기술', '기술 관련 게시글', 'Y', 2, 'SYSTEM'),
('NTTCATEGORY', 'NTTCAT03', '업무', '업무 관련 게시글', 'Y', 3, 'SYSTEM'),
('NTTCATEGORY', 'NTTCAT04', '기타', '기타 게시글', 'Y', 4, 'SYSTEM')
ON CONFLICT (CODE_ID, CODE) DO NOTHING;

-- 5. 인덱스 생성 (성능 향상)
CREATE INDEX IF NOT EXISTS IDX_COMTNBBS_BBS_ID_STATUS ON COMTNBBS(BBS_ID, NTT_STATUS_CODE);
CREATE INDEX IF NOT EXISTS IDX_COMTNBBS_CATEGORY ON COMTNBBS(NTT_CATEGORY);
CREATE INDEX IF NOT EXISTS IDX_COMTNBBS_PRIORITY ON COMTNBBS(NTT_PRIORITY);
CREATE INDEX IF NOT EXISTS IDX_COMTNBBS_EXPIRY_DATE ON COMTNBBS(NTT_EXPIRY_DATE);
CREATE INDEX IF NOT EXISTS IDX_COMTNBBS_VIEW_COUNT ON COMTNBBS(NTT_VIEW_COUNT);

-- 6. 기존 게시판에 기본값 설정
UPDATE COMTNBBSMST 
SET BBS_TY_CODE = 'BBST01', 
    BBS_ATTRB_CODE = 'BBSA01',
    BBS_STATUS_CODE = 'BBSSTATUS01'
WHERE BBS_TY_CODE IS NULL OR BBS_ATTRB_CODE IS NULL;

-- 7. 기존 게시글에 기본값 설정
UPDATE COMTNBBS 
SET NTT_STATUS_CODE = 'NTTSTATUS01',
    NTT_CATEGORY = 'NTTCAT01'
WHERE NTT_STATUS_CODE IS NULL OR NTT_CATEGORY IS NULL;

-- 8. 생성된 구조 확인
SELECT 
    '게시판 마스터 확장' as 테이블,
    column_name as 컬럼명,
    data_type as 데이터타입,
    is_nullable as NULL허용
FROM information_schema.columns 
WHERE table_name = 'comtnbbsmst' 
ORDER BY ordinal_position;

SELECT 
    '게시글 확장' as 테이블,
    column_name as 컬럼명,
    data_type as 데이터타입,
    is_nullable as NULL허용
FROM information_schema.columns 
WHERE table_name = 'comtnbbs' 
ORDER BY ordinal_position; 