-- PostgreSQL Database Initialization Script for OpenSurvey
-- 전자정부 프레임워크 표준 공통코드 테이블 구조

-- 공통코드 분류 테이블
CREATE TABLE IF NOT EXISTS COMTCCMMNCLCODE (
    CL_CODE CHAR(3) NOT NULL,
    CL_CODE_NM VARCHAR(60) DEFAULT NULL,
    CL_CODE_DC VARCHAR(200) DEFAULT NULL,
    USE_AT CHAR(1) DEFAULT NULL,
    FRST_REGIST_PNTTM TIMESTAMP DEFAULT NULL,
    FRST_REGISTER_ID VARCHAR(20) DEFAULT NULL,
    LAST_UPDT_PNTTM TIMESTAMP DEFAULT NULL,
    LAST_UPDUSR_ID VARCHAR(20) DEFAULT NULL,
    PRIMARY KEY (CL_CODE)
);

-- 공통코드 그룹 테이블
CREATE TABLE IF NOT EXISTS COMTCCMMNCODE (
    CODE_ID VARCHAR(20) NOT NULL,
    CODE_ID_NM VARCHAR(60) DEFAULT NULL,
    CODE_ID_DC VARCHAR(200) DEFAULT NULL,
    USE_AT CHAR(1) DEFAULT NULL,
    CL_CODE CHAR(3) DEFAULT NULL,
    FRST_REGIST_PNTTM TIMESTAMP DEFAULT NULL,
    FRST_REGISTER_ID VARCHAR(20) DEFAULT NULL,
    LAST_UPDT_PNTTM TIMESTAMP DEFAULT NULL,
    LAST_UPDUSR_ID VARCHAR(20) DEFAULT NULL,
    PRIMARY KEY (CODE_ID)
);

-- 공통코드 상세 테이블
CREATE TABLE IF NOT EXISTS COMTCCMMNDETAILCODE (
    CODE_ID VARCHAR(20) NOT NULL,
    CODE VARCHAR(50) NOT NULL,
    CODE_NM VARCHAR(60) DEFAULT NULL,
    CODE_DC VARCHAR(200) DEFAULT NULL,
    USE_AT CHAR(1) DEFAULT NULL,
    FRST_REGIST_PNTTM TIMESTAMP DEFAULT NULL,
    FRST_REGISTER_ID VARCHAR(20) DEFAULT NULL,
    LAST_UPDT_PNTTM TIMESTAMP DEFAULT NULL,
    LAST_UPDUSR_ID VARCHAR(20) DEFAULT NULL,
    PRIMARY KEY (CODE_ID, CODE),
    CONSTRAINT COMTCCMMNDETAILCODE_FK1 FOREIGN KEY (CODE_ID) REFERENCES COMTCCMMNCODE (CODE_ID)
);

-- 설문조사 테이블 생성
CREATE TABLE IF NOT EXISTS SURVEY (
    SURVEY_ID SERIAL PRIMARY KEY,
    SURVEY_TITLE VARCHAR(200) NOT NULL,
    SURVEY_DESCRIPTION TEXT,
    START_DATE DATE,
    END_DATE DATE,
    STATUS VARCHAR(20) DEFAULT 'DRAFT',
    USE_AT CHAR(1) DEFAULT 'Y',
    REGIST_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REGIST_USER VARCHAR(20),
    UPDATE_DATE TIMESTAMP,
    UPDATE_USER VARCHAR(20)
);

-- 설문조사 문항 테이블 생성
CREATE TABLE IF NOT EXISTS SURVEY_QUESTION (
    QUESTION_ID SERIAL PRIMARY KEY,
    SURVEY_ID INTEGER NOT NULL,
    QUESTION_TEXT TEXT NOT NULL,
    QUESTION_TYPE VARCHAR(20) NOT NULL,
    QUESTION_ORDER INTEGER NOT NULL,
    REQUIRED CHAR(1) DEFAULT 'N',
    USE_AT CHAR(1) DEFAULT 'Y',
    REGIST_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REGIST_USER VARCHAR(20),
    UPDATE_DATE TIMESTAMP,
    UPDATE_USER VARCHAR(20),
    FOREIGN KEY (SURVEY_ID) REFERENCES SURVEY(SURVEY_ID)
);

-- 설문조사 응답 테이블 생성
CREATE TABLE IF NOT EXISTS SURVEY_RESPONSE (
    RESPONSE_ID SERIAL PRIMARY KEY,
    SURVEY_ID INTEGER NOT NULL,
    RESPONDENT_NAME VARCHAR(100),
    RESPONDENT_EMAIL VARCHAR(200),
    RESPONSE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USE_AT CHAR(1) DEFAULT 'Y',
    REGIST_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REGIST_USER VARCHAR(20),
    UPDATE_DATE TIMESTAMP,
    UPDATE_USER VARCHAR(20),
    FOREIGN KEY (SURVEY_ID) REFERENCES SURVEY(SURVEY_ID)
);

-- 설문조사 응답 상세 테이블 생성
CREATE TABLE IF NOT EXISTS SURVEY_RESPONSE_DETAIL (
    RESPONSE_DETAIL_ID SERIAL PRIMARY KEY,
    RESPONSE_ID INTEGER NOT NULL,
    QUESTION_ID INTEGER NOT NULL,
    ANSWER_TEXT TEXT,
    ANSWER_VALUE VARCHAR(500),
    REGIST_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REGIST_USER VARCHAR(20),
    UPDATE_DATE TIMESTAMP,
    UPDATE_USER VARCHAR(20),
    FOREIGN KEY (RESPONSE_ID) REFERENCES SURVEY_RESPONSE(RESPONSE_ID),
    FOREIGN KEY (QUESTION_ID) REFERENCES SURVEY_QUESTION(QUESTION_ID)
);

-- 공통코드 분류 데이터
INSERT INTO COMTCCMMNCLCODE (CL_CODE, CL_CODE_NM, CL_CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID) VALUES
('SYS', '시스템 코드', '시스템 관련 공통코드', 'Y', CURRENT_TIMESTAMP, 'SYSTEM');

-- 설문조사 관련 공통코드 그룹 데이터
INSERT INTO COMTCCMMNCODE (CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, CL_CODE, FRST_REGIST_PNTTM, FRST_REGISTER_ID) VALUES
('SURVEY_STATUS', '설문 상태', '설문조사의 상태 구분', 'Y', 'SYS', CURRENT_TIMESTAMP, 'SYSTEM'),
('QUESTION_TYPE', '질문 유형', '설문 질문의 유형 구분', 'Y', 'SYS', CURRENT_TIMESTAMP, 'SYSTEM'),
('SURVEY_CATEGORY', '설문 카테고리', '설문조사의 카테고리 구분', 'Y', 'SYS', CURRENT_TIMESTAMP, 'SYSTEM'),
('ADMIN_AUTHORITY', '관리자 권한', '관리자 권한 구분', 'Y', 'SYS', CURRENT_TIMESTAMP, 'SYSTEM');

-- 설문 상태 코드 상세
INSERT INTO COMTCCMMNDETAILCODE (CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID) VALUES
('SURVEY_STATUS', 'DRAFT', '임시저장', '설문 작성 중', 'Y', CURRENT_TIMESTAMP, 'SYSTEM'),
('SURVEY_STATUS', 'PUBLISHED', '배포중', '설문 배포 중', 'Y', CURRENT_TIMESTAMP, 'SYSTEM'),
('SURVEY_STATUS', 'CLOSED', '종료', '설문 종료', 'Y', CURRENT_TIMESTAMP, 'SYSTEM'),
('SURVEY_STATUS', 'ARCHIVED', '보관', '설문 보관', 'Y', CURRENT_TIMESTAMP, 'SYSTEM');

-- 질문 유형 코드 상세
INSERT INTO COMTCCMMNDETAILCODE (CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID) VALUES
('QUESTION_TYPE', 'TEXT', '주관식', '자유 텍스트 입력', 'Y', CURRENT_TIMESTAMP, 'SYSTEM'),
('QUESTION_TYPE', 'RADIO', '객관식(단일)', '단일 선택 객관식', 'Y', CURRENT_TIMESTAMP, 'SYSTEM'),
('QUESTION_TYPE', 'CHECKBOX', '객관식(복수)', '복수 선택 객관식', 'Y', CURRENT_TIMESTAMP, 'SYSTEM'),
('QUESTION_TYPE', 'SCALE', '척도형', '1-5점 척도', 'Y', CURRENT_TIMESTAMP, 'SYSTEM'),
('QUESTION_TYPE', 'DATE', '날짜', '날짜 선택', 'Y', CURRENT_TIMESTAMP, 'SYSTEM'),
('QUESTION_TYPE', 'FILE', '파일업로드', '파일 업로드', 'Y', CURRENT_TIMESTAMP, 'SYSTEM');

-- 설문 카테고리 코드 상세
INSERT INTO COMTCCMMNDETAILCODE (CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID) VALUES
('SURVEY_CATEGORY', 'CUSTOMER_SATISFACTION', '고객만족도', '고객 만족도 조사', 'Y', CURRENT_TIMESTAMP, 'SYSTEM'),
('SURVEY_CATEGORY', 'MARKET_RESEARCH', '시장조사', '시장 조사', 'Y', CURRENT_TIMESTAMP, 'SYSTEM'),
('SURVEY_CATEGORY', 'EMPLOYEE_SATISFACTION', '직원만족도', '직원 만족도 조사', 'Y', CURRENT_TIMESTAMP, 'SYSTEM'),
('SURVEY_CATEGORY', 'ACADEMIC_RESEARCH', '학술조사', '학술 연구 조사', 'Y', CURRENT_TIMESTAMP, 'SYSTEM'),
('SURVEY_CATEGORY', 'SOCIAL_RESEARCH', '사회조사', '사회 현상 조사', 'Y', CURRENT_TIMESTAMP, 'SYSTEM'),
('SURVEY_CATEGORY', 'ETC', '기타', '기타 설문조사', 'Y', CURRENT_TIMESTAMP, 'SYSTEM');

-- 관리자 권한 상세코드
INSERT INTO COMTCCMMNDETAILCODE (CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID) VALUES
('ADMIN_AUTHORITY', 'SYSTEM_ADMIN', '시스템 관리자', '시스템 전체 관리 권한', 'Y', CURRENT_TIMESTAMP, 'SYSTEM'),
('ADMIN_AUTHORITY', 'SUPER_ADMIN', '슈퍼 관리자', '슈퍼 관리자 권한', 'Y', CURRENT_TIMESTAMP, 'SYSTEM'),
('ADMIN_AUTHORITY', 'STAFF_ADMIN', '직원 관리자', '직원 관리 권한', 'Y', CURRENT_TIMESTAMP, 'SYSTEM'),
('ADMIN_AUTHORITY', 'ADMIN', '업무 관리자', '업무 관리 권한', 'Y', CURRENT_TIMESTAMP, 'SYSTEM');

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS COMTCCMMNCODE_i01 ON COMTCCMMNCODE (CL_CODE);
CREATE INDEX IF NOT EXISTS COMTCCMMNDETAILCODE_i01 ON COMTCCMMNDETAILCODE (CODE_ID);
CREATE INDEX IF NOT EXISTS IDX_SURVEY_STATUS ON SURVEY(STATUS);
CREATE INDEX IF NOT EXISTS IDX_SURVEY_USE_AT ON SURVEY(USE_AT);
CREATE INDEX IF NOT EXISTS IDX_SURVEY_QUESTION_SURVEY_ID ON SURVEY_QUESTION(SURVEY_ID);
CREATE INDEX IF NOT EXISTS IDX_SURVEY_RESPONSE_SURVEY_ID ON SURVEY_RESPONSE(SURVEY_ID);
CREATE INDEX IF NOT EXISTS IDX_SURVEY_RESPONSE_DETAIL_RESPONSE_ID ON SURVEY_RESPONSE_DETAIL(RESPONSE_ID); 