-- 사용자 테이블 생성
CREATE TABLE IF NOT EXISTS USER_INFO (
    USER_ID VARCHAR(20) NOT NULL,
    USER_NM VARCHAR(60) NOT NULL,
    PASSWORD VARCHAR(200) NOT NULL,
    EMAIL VARCHAR(100),
    PHONE VARCHAR(20),
    DEPT_NM VARCHAR(100),
    POSITION_NM VARCHAR(50),
    AUTHORITY_CODE VARCHAR(50) NOT NULL,
    USE_AT CHAR(1) DEFAULT 'Y',
    REGIST_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REGIST_USER VARCHAR(20),
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_USER VARCHAR(20),
    PRIMARY KEY (USER_ID)
);

-- 초기 사용자 데이터 삽입 (평문 비밀번호)
INSERT INTO USER_INFO (USER_ID, USER_NM, PASSWORD, EMAIL, DEPT_NM, POSITION_NM, AUTHORITY_CODE, USE_AT, REGIST_USER) VALUES
('admin', '시스템관리자', 'admin123', 'admin@opensurvey.com', '시스템관리팀', '시스템관리자', 'SYSTEM_ADMIN', 'Y', 'SYSTEM')
ON CONFLICT (USER_ID) DO NOTHING;

INSERT INTO USER_INFO (USER_ID, USER_NM, PASSWORD, EMAIL, DEPT_NM, POSITION_NM, AUTHORITY_CODE, USE_AT, REGIST_USER) VALUES
('survey_admin', '설문관리자', 'survey123', 'survey@opensurvey.com', '설문관리팀', '설문관리자', 'STAFF_ADMIN', 'Y', 'SYSTEM')
ON CONFLICT (USER_ID) DO NOTHING;

INSERT INTO USER_INFO (USER_ID, USER_NM, PASSWORD, EMAIL, DEPT_NM, POSITION_NM, AUTHORITY_CODE, USE_AT, REGIST_USER) VALUES
('user', '일반사용자', 'user123', 'user@opensurvey.com', '일반부서', '사원', 'ADMIN', 'Y', 'SYSTEM')
ON CONFLICT (USER_ID) DO NOTHING; 